export const LEVEL_UP_PLAN_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    can_proceed: { type: 'boolean' },
    needs_advancement_profile: { type: 'boolean' },
    source_kind: { type: 'string', enum: ['supported_srd', 'player_profile', 'needs_profile'] },
    source_label: { type: 'string' },
    advancing_class: { type: 'string' },
    target_total_level: { type: 'integer', minimum: 1, maximum: 20 },
    target_class_level: { type: 'integer', minimum: 1, maximum: 20 },
    proficiency_bonus: { type: 'string' },
    automatic_changes: { type: 'array', items: { type: 'string' } },
    feature_names: { type: 'array', items: { type: 'string' } },
    progression_values: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: { name: { type: 'string' }, value: { type: 'string' } },
        required: ['name', 'value'],
      },
    },
    spell_slots: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: { level: { type: 'string' }, total: { type: 'string' } },
        required: ['level', 'total'],
      },
    },
    choices: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          id: { type: 'string' },
          label: { type: 'string' },
          help: { type: 'string' },
          required: { type: 'boolean' },
          options: { type: 'array', items: { type: 'string' } },
          choice_kind: { type: 'string', enum: ['other', 'spellbook', 'prepared_spell', 'known_spell', 'cantrip'] },
          selection_count: { type: 'integer', minimum: 1, maximum: 20 },
        },
        required: ['id', 'label', 'help', 'required', 'options', 'choice_kind', 'selection_count'],
      },
    },
    warnings: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'can_proceed',
    'needs_advancement_profile',
    'source_kind',
    'source_label',
    'advancing_class',
    'target_total_level',
    'target_class_level',
    'proficiency_bonus',
    'automatic_changes',
    'feature_names',
    'progression_values',
    'spell_slots',
    'choices',
    'warnings',
  ],
} as const
