import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (relative: string) => fs.readFileSync(path.join(root, relative), 'utf8')
const exists = (relative: string) => fs.existsSync(path.join(root, relative))

const pkg = JSON.parse(read('package.json')) as { name?: string; version?: string; rpgywVersion?: string; dependencies?: Record<string,string> }
assert.equal(pkg.name, 'rpg-your-way')
assert.equal(pkg.version, '1.10.0')
assert.equal(pkg.rpgywVersion, '1.10.0')
assert.match(read('lib/version.ts'), /APP_VERSION = '1\.10\.0'/)

for (const file of [
  'app/page.tsx', 'app/play/page.tsx', 'app/start/page.tsx', 'app/script/page.tsx', 'app/shape/page.tsx',
  'app/account/page.tsx', 'app/pricing/page.tsx', 'app/pricing/actions.ts',
  'app/api/shape/jobs/route.ts', 'app/api/shape/quote/route.ts', 'app/api/shape/transform/route.ts',
  'app/api/shape/projects/route.ts', 'app/api/shape/usage/route.ts', 'app/api/stripe/webhook/route.ts',
  'components/SiteHeader.tsx', 'components/SiteFooter.tsx', 'components/ShapeWorkspace.tsx', 'components/PersistentPlayModal.tsx',
  'lib/billing/play-packs.ts', 'lib/shape/billing.ts', 'lib/shape/settlement.ts', 'lib/shape/transcript.ts',
  'lib/stripe/server.ts', 'lib/stripe/checkout.ts', 'lib/usage/money.ts', 'lib/usage/openai-cost.ts',
  'supabase/migrations/20260825003000_shared_usage_balance.sql',
  'supabase/migrations/20260825060000_script_commercial_billing.sql',
  'supabase/migrations/20260825120000_play_provider_usage.sql',
  'app/api/play/access/route.ts',
  'app/api/aigm/gameplay-chat/route.ts',
  'app/api/aigm/speech/route.ts',
  'app/api/aigm/transcribe/route.ts',
  'components/aigm/rpgyw-start-entry.tsx',
  'components/start/StartOnboarding.tsx',
  'app/api/aigm/character-intake/route.ts',
  'app/api/aigm/character-clarify/route.ts',
  'app/api/start/help/route.ts',
  'lib/aigm/character-intake-prompt.ts',
  'lib/start/help-knowledge.ts',
  'components/account/DeleteAccountControl.tsx',
  'components/aigm/aigm-gameplay-shell.tsx',
  'lib/aigm/campaign-storage.ts',
  'lib/aigm/campaign-persistence.ts',
  'lib/aigm/character-display-rules.ts',
  'lib/usage/owner-qa.ts',
  'lib/usage/play-cost.ts',
  'lib/usage/server-billing.ts',
  'lib/usage/audio-cost.ts',
  'lib/usage/play-turn-billing.ts',
  'app/api/aigm/turn-billing/audio-complete/route.ts',
  'supabase/migrations/20260828002500_play_turn_voice_billing.sql',
  'scripts/test-audio-cost.mts',
  'README-1.8.12.md',
  'README-1.9.0.md',
  'README-1.9.2.md',
  'README-1.9.3.md',
  'README-1.9.4.md',
  'README-1.10.0.md',
  'ACCESSIBILITY.md',
  'app/accessibility/page.tsx',
  'scripts/validate-accessibility.mts',
  'postcss.config.mjs',
  'data/settings/eberron.json',
  'data/rules/corpora/dnd-5.5e-srd-5.2.1.json',
]) assert.ok(exists(file), `Missing ${file}`)

const account = read('app/account/page.tsx')
for (const phrase of [
  'Sign in or create an account', 'Usage balance', 'Available for Play and Script', 'Add usage',
  'Purchase price includes payment processing and a small site operating contribution', '2.9% + 30¢',
  'What am I getting for my money?', 'RPG Your Way sells prepaid usage, not turns.',
  'about 20–30 turns', 'about 360–540 turns', 'Usage to date', 'Where your balance has gone',
  'AI processing', 'Talk-to-text', 'AI readback', 'Play Pack purchases', 'Purchase history',
  'RPG Your Way does not show a turn-by-turn charge list.',
]) assert.match(account, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
assert.doesNotMatch(account, /Lifetime added|Lifetime used|No separate Script wallet|Recent activity|signedUsageDollars/)

const packs = read('lib/billing/play-packs.ts')
for (const amount of ['priceCents: 572', 'priceCents: 1_653', 'priceCents: 3_275', 'priceCents: 4_897', 'priceCents: 7_060', 'priceCents: 9_763']) assert.match(packs, new RegExp(amount))
for (const operating of ['siteOperatingCents: 25', 'siteOperatingCents: 75', 'siteOperatingCents: 150', 'siteOperatingCents: 225', 'siteOperatingCents: 325', 'siteOperatingCents: 450']) assert.match(packs, new RegExp(operating))
for (const usage of ['usageCents: 500', 'usageCents: 1_500', 'usageCents: 3_000', 'usageCents: 4_500', 'usageCents: 6_500', 'usageCents: 9_000']) assert.match(packs, new RegExp(usage))

const layout = read('app/layout.tsx')
assert.match(layout, /@vercel\/analytics\/next/)
assert.match(layout, /<Analytics \/>/)

const header = read('components/SiteHeader.tsx')
assert.match(header, /href: '\/account', label: 'Account'/)
assert.match(header, /thereadingofthewardens\.com/)
assert.match(header, /target="_blank"/)
assert.match(header, /fullscreen-nav-gap/)
assert.match(header, /Your AI GM/)
const css = read('app/globals.css')
assert.match(css, /header-inner \{ min-height: 52px/)
assert.match(css, /usage-disclosure-row/)
assert.match(css, /kofi-support-button/)
assert.match(css, /shape-quote/)

const footer = read('components/SiteFooter.tsx')
assert.match(footer, /Buy Brett a Coffee/)
assert.match(footer, /ko-fi\.com\/dodoink/)
assert.match(footer, /fill="#FF5E5B"/)
assert.match(footer, /kofi-cup/)

const home = read('app/page.tsx')
assert.match(home, /href="\/start">Start A New Campaign<\/Link>/)
assert.match(home, /PageShell headerVariant="landing"/)
assert.match(home, /Why I created RPG Your Way\./)
assert.match(home, /Who benefits from this site\?/)
assert.match(home, /Play when you have time/)
assert.match(home, /<LandingCampaignPanel \/>/)
const landingCampaignPanel193 = read('components/LandingCampaignPanel.tsx')
assert.doesNotMatch(landingCampaignPanel193, /16 Hammer 1501 DR/)
assert.doesNotMatch(home, /Warning: AI GM ahead/)
assert.doesNotMatch(home, /Open Now/)
assert.doesNotMatch(home, /Tabletop gaming is best in person/)
assert.match(read('app/start/page.tsx'), /<RpgywStartEntry \/>/)

const pricing = read('app/pricing/page.tsx')
assert.match(pricing, /permanentRedirect\('\/account#add-usage'\)/)

const scriptPage = read('app/script/page.tsx')
assert.match(scriptPage, /same prepaid RPG Your Way usage balance as Play/)
assert.match(scriptPage, /maximum estimated balance deduction/)
assert.doesNotMatch(scriptPage, /private test|no payment is collected/i)

const workspace = read('components/ShapeWorkspace.tsx')
assert.match(workspace, /See maximum usage/)
assert.match(workspace, /Begin Script · max/)
assert.match(workspace, /Maximum estimated deduction/)
assert.match(workspace, /Progress advances only when a real Script step finishes/)
assert.match(workspace, /role="progressbar"/)
assert.match(workspace, /setQuoteMicrousd\(null\)/)
assert.match(workspace, /Add usage in Account/)
assert.doesNotMatch(workspace, /Begin private Script test|Script opens soon|Preview only/)

const jobs = read('app/api/shape/jobs/route.ts')
assert.match(jobs, /estimateShapeMaximumMicrousd/)
assert.match(jobs, /rpgyw_reserve_usage/)
assert.match(jobs, /maximum_deduction_microusd/)
assert.match(jobs, /settleShapeJobUsage/)
assert.doesNotMatch(jobs, /shapeEmailAllowed|private test list/)

const transform = read('app/api/shape/transform/route.ts')
assert.match(transform, /cache_write_tokens/)
assert.match(transform, /settleCompletedJob/)
assert.match(transform, /section_disposition/)
assert.match(transform, /no_new_prose/)
assert.doesNotMatch(transform, /diagnostic:\s*message/)
assert.doesNotMatch(transform, /shapeEmailAllowed|private test list/)

const settlement = read('lib/shape/settlement.ts')
assert.match(settlement, /roundUsageMicrousdToCent\(providerCostMicrousd\)/)
assert.match(settlement, /Math\.min\(roundedProviderCostMicrousd, maximumMicrousd\)/)
assert.match(settlement, /rpgyw_capture_usage/)
assert.match(settlement, /cache_write_tokens/)

const stripe = read('lib/stripe/server.ts')
assert.match(stripe, /latest_charge\.balance_transaction/)
assert.match(stripe, /processingSurplusCents/)
assert.match(stripe, /stripe-surplus/)
assert.match(stripe, /account\?status=checkout-cancelled#add-usage/)

const migration = read('supabase/migrations/20260825060000_script_commercial_billing.sql')
assert.match(migration, /cache_write_tokens/)
assert.match(migration, /usage_hold_id/)
assert.match(migration, /maximum_deduction_microusd/)
assert.match(migration, /provider_cost_microusd/)
assert.match(migration, /billed_microusd/)


const playPage = read('app/play/page.tsx')
assert.match(playPage, /<AigmGameplayShell \/>/)
assert.match(playPage, /MotionPreferenceProvider/)
assert.match(playPage, /<MotionPreferenceProvider>/)
assert.match(playPage, /redirect\('\/start'\)/)
assert.doesNotMatch(playPage, /Import Existing Adventure|RpgywPlayEntry/)

const startPage = read('app/start/page.tsx')
assert.match(startPage, /<RpgywStartEntry \/>/)
assert.match(startPage, /Build a new campaign here, or import an existing WardensPC or RPG Your Way adventure/)
const startEntry = read('components/aigm/rpgyw-start-entry.tsx')
assert.match(startEntry, /Import Existing Adventure/)
assert.match(startEntry, /parseAdventureState/)
assert.match(startEntry, /imported\.stage !== 'complete'/)
assert.match(startEntry, /window\.location\.assign\('\/play'\)/)
assert.match(startEntry, /There is no cloud campaign synchronization/)
assert.doesNotMatch(startEntry, /setPlaying|AigmGameplayShell/)
const gameplayShell = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplayShell, /Go to Start/)
assert.match(gameplayShell, /href="\/start"/)

const campaignPersistence = read('lib/aigm/campaign-persistence.ts')
assert.match(campaignPersistence, /rpgyw-aigm-campaigns/)
assert.doesNotMatch(campaignPersistence, /wardenspc-aigm-campaigns/)

const ownerQa = read('lib/usage/owner-qa.ts')
assert.match(ownerQa, /OWNER_QA_EMAIL = 'brett@rpgyourway\.com'/)
assert.doesNotMatch(ownerQa, /@.*@/)

const gameplay = read('app/api/aigm/gameplay-chat/route.ts')
assert.match(gameplay, /requireUsageAccount/)
assert.match(gameplay, /reserveUsage/)
assert.doesNotMatch(gameplay, /settleUsage/)
assert.match(gameplay, /recordPlayTurnComponent/)
assert.match(gameplay, /markGameplayComplete/)
assert.match(gameplay, /attachPlayTurnReservation/)
assert.match(gameplay, /narration_expected/)
assert.match(gameplay, /terraProviderCostMicrousd/)
assert.match(gameplay, /usage_billing/)
assert.match(gameplay, /x-rpgyw-operation-id/)

const billing = read('lib/usage/server-billing.ts')
assert.match(billing, /rpgyw_reserve_usage/)
assert.match(billing, /rpgyw_capture_usage/)
assert.match(billing, /roundUsageMicrousdToCent/)
assert.match(billing, /ownerQa/)
assert.match(billing, /provider_usage_events/)

const playAccess = read('app/api/play/access/route.ts')
assert.match(playAccess, /voice_available:\s*true/)
const speech = read('app/api/aigm/speech/route.ts')
const transcribe = read('app/api/aigm/transcribe/route.ts')
assert.doesNotMatch(speech, /if \(!account\.ownerQa\)/)
assert.doesNotMatch(transcribe, /if \(!account\.ownerQa\)/)

const shapeJobs = read('app/api/shape/jobs/route.ts')
assert.match(shapeJobs, /isOwnerQaEmail/)
assert.match(shapeJobs, /if \(!auth\.ownerQa\)/)
const shapeSettlement = read('lib/shape/settlement.ts')
assert.match(shapeSettlement, /ownerQa/)
assert.match(shapeSettlement, /billed_microusd: 0/)

const playMigration = read('supabase/migrations/20260825120000_play_provider_usage.sql')
assert.match(playMigration, /provider_usage_events/)
assert.match(playMigration, /owner_qa_exempt/)
assert.match(playMigration, /no browser read\/write policies/i)

assert.equal(pkg.dependencies?.['@vercel/analytics'], '^1.5.0')
assert.equal(pkg.dependencies?.['lucide-react'], '^1.16.0')
const devDependencies = (pkg as { devDependencies?: Record<string,string> }).devDependencies || {}
assert.equal(devDependencies['tailwindcss'], '^4.3.3')
assert.equal(devDependencies['@tailwindcss/postcss'], '^4.3.3')
assert.match(read('postcss.config.mjs'), /@tailwindcss\/postcss/)

const env = read('.env.example')
assert.match(env, /OPENAI_API_KEY=/)
assert.match(env, /OPENAI_AUDIO_API_KEY=/)
assert.match(env, /OPENAI_TTS_API_KEY=/)
assert.match(env, /OPENAI_TRANSCRIBE_API_KEY=/)
assert.match(env, /OPENAI_TTS_MODEL=gpt-4o-mini-tts/)
assert.match(env, /OPENAI_TRANSCRIBE_MODEL=gpt-4o-mini-transcribe/)
assert.match(env, /STRIPE_SECRET_KEY=/)
assert.match(env, /STRIPE_WEBHOOK_SECRET=/)
assert.match(env, /SUPABASE_SERVICE_ROLE_KEY=/)
assert.doesNotMatch(env, /RPGYW_SHAPE_BETA_EMAILS/)

for (const productionFile of ['lib/stripe/checkout.ts', 'lib/shape/billing.ts', 'lib/shape/settlement.ts']) {
  assert.doesNotMatch(read(productionFile), /from ['"][^'"]+\.ts['"]/, `${productionFile} must not import .ts extensions.`)
}


const playAccess175 = read('app/api/play/access/route.ts')
assert.match(playAccess175, /voice_available:\s*true/)
assert.doesNotMatch(playAccess175, /voice_available:\s*account\.ownerQa/)
for (const voiceRoute175 of ['app/api/aigm/speech/route.ts', 'app/api/aigm/transcribe/route.ts']) {
  const source175 = read(voiceRoute175)
  assert.match(source175, /await requireUsageAccount\(\)/)
  assert.doesNotMatch(source175, /if \(!account\.ownerQa\)/)
  assert.doesNotMatch(source175, /being readied for prepaid Play billing/)
}
const gameplay175 = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplay175, /aigm-character-reorder/)
assert.match(gameplay175, /Character record/)
assert.doesNotMatch(gameplay175, /Complete character record/)
assert.match(gameplay175, /character-sheet-dialog/)
assert.match(gameplay175, /character-sheet-actions/)
assert.match(gameplay175, /aigm-gameplay-send/)
const voiceControls175 = read('components/aigm/aigm-voice-controls.tsx')
assert.match(voiceControls175, /aigm-voice-controls/)
const css175 = read('app/globals.css')
assert.match(css175, /RPG Your Way 1\.7\.5 Play UI and voice cleanup/)
assert.match(css175, /grid-template-columns:\s*minmax\(230px, \.64fr\)/)
assert.match(css175, /\.aigm-character-reorder/)
assert.match(css175, /\.character-sheet-dialog/)

console.log('RPG Your Way 1.7.5 Play UI and voice cleanup checks passed.')


const gameplay179 = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplay179, /aigm-conversation-column/)
assert.match(gameplay179, /aigm-message-wrap/)
assert.match(gameplay179, /Initiative <span className="inline-block whitespace-nowrap">&amp; Dice<\/span>/)
assert.doesNotMatch(gameplay179, /\b(?:bg|text|border)-accent(?:-foreground)?(?:\/[\w.-]+)?\b/)
const css179 = read('app/globals.css')
assert.match(css179, /RPG Your Way 1\.7\.9 recovered Play layout and color cleanup/)
assert.match(css179, /grid-template-columns:\s*minmax\(260px, \.78fr\) minmax\(0, 2\.4fr\) minmax\(250px, \.86fr\)/)
assert.match(css179, /\.aigm-assistant-message\s*\{\s*max-width:\s*calc\(100% - 3rem\)/)
const access179 = read('app/api/play/access/route.ts')
assert.match(access179, /voice_available:\s*true/)
assert.doesNotMatch(access179, /voice_available:\s*account\.ownerQa/)

console.log('RPG Your Way 1.7.9 recovery, voice-validator, and Play presentation checks passed.')


const gameplay1710 = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplay1710, /aigm-gameplay-summary/)
assert.match(gameplay1710, /rows=\{2\}/)
assert.match(gameplay1710, /onReorder=\{reorderPartyCharacter\}/)
assert.match(gameplay1710, /pointerDraggingRef/)
assert.match(gameplay1710, /aigm-session-help/)
assert.match(gameplay1710, /data-open=\{sessionToolsOpen/)
assert.doesNotMatch(gameplay1710, /Current party<\/p>/)
const authPanel1710 = read('components/AuthPanel.tsx')
assert.match(authPanel1710, /Confirm password/)
assert.match(authPanel1710, /name="confirmPassword"/)
const authActions1710 = read('app/account/actions.ts')
assert.match(authActions1710, /password !== confirmPassword/)
const authPrompt1710 = read('components/AuthPrompt.tsx')
assert.match(authPrompt1710, /Not now\. I just want to look around\./)
const css1710 = read('app/globals.css')
assert.match(css1710, /RPG Your Way 1\.7\.12 Play space-reclamation and account-entry cleanup/)
assert.match(css1710, /minmax\(230px, \.68fr\) minmax\(0, 2\.85fr\) minmax\(240px, \.72fr\)/)
assert.match(css1710, /aigm-session-tools\[data-open="true"\]/)
assert.match(css1710, /\.auth-not-now \{[\s\S]*width: 100%/)

console.log('RPG Your Way 1.7.12 Play space and account-entry checks passed.')


const gameplay1714 = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplay1714, />Purist<\/button>/)
assert.match(gameplay1714, /<span className="text-center leading-tight">Story<br \/>first<\/span><\/button>/)
assert.match(gameplay1714, />How many dice\?<\/label>/)
assert.match(gameplay1714, />Of which kind\?<\/p>/)
assert.match(gameplay1714, /Can I direct my game\?/)
assert.match(gameplay1714, /Drag to reorder/)
assert.match(gameplay1714, /const \[dragging, setDragging\] = useState\(false\)/)

const siteHeader1714 = read('components/SiteHeader.tsx')
assert.match(siteHeader1714, /\{ href: '\/start', label: 'Start' \}/)
assert.match(siteHeader1714, /\{ href: '\/account', label: 'Account' \}/)

const playPage1714 = read('app/play/page.tsx')
assert.match(playPage1714, /play-page-frame/)
assert.match(playPage1714, /<SiteHeader \/>/)
assert.match(playPage1714, /<MotionPreferenceProvider>/)
assert.match(playPage1714, /<AigmGameplayShell \/>/)

const landing1714 = read('app/page.tsx')
assert.match(landing1714, /PageShell headerVariant="landing"/)
assert.match(landing1714, /Why I created RPG Your Way\./)
assert.match(landing1714, /Who benefits from this site\?/)
assert.match(landing1714, /<LandingCampaignPanel \/>/)
assert.match(landing1714, />Start A New Campaign<\/Link>/)
assert.doesNotMatch(landing1714, /~~ Warning: AI GM ahead ~~/)
assert.doesNotMatch(landing1714, /Open Now/)
assert.doesNotMatch(landing1714, /Tabletop gaming is best in person\. No question\./)

const campaignPanel1714 = read('components/LandingCampaignPanel.tsx')
assert.match(campaignPanel1714, /Return to Adventure/)
assert.match(campaignPanel1714, /available_display/)
assert.match(campaignPanel1714, /loadAdventureState/)
assert.match(campaignPanel1714, /CURRENT_ADVENTURE_KEY/)

const css1714 = read('app/globals.css')
assert.match(css1714, /RPG Your Way 1\.7\.14 Play \+ landing return pass/)
assert.match(css1714, /translateY\(calc\(-100% \+ 4px\)\)/)
assert.match(css1714, /\.landing-return-grid/)
assert.match(css1714, /\.landing-campaign-snippet/)
assert.match(css1714, /\.fullscreen-nav-gap\s*\{\s*margin-left:\s*\.25rem/)

console.log('RPG Your Way 1.7.16 landing-validator hotfix checks passed.')

const landingCampaignCurrent = read('components/LandingCampaignPanel.tsx')
assert.match(landingCampaignCurrent, /Return to Adventure/)


const landing1717 = read('app/page.tsx')
assert.match(landing1717, />Start A New Campaign<\/Link>/)
assert.match(landing1717, /<WhyCreatedAccordion \/>/)
assert.match(landing1717, /<AudienceAccordion \/>/)

const campaign1717 = read('components/LandingCampaignPanel.tsx')
assert.match(campaign1717, /Return to Adventure/)
assert.doesNotMatch(campaign1717, /Return to Playing/)

const css1717 = read('app/globals.css')
assert.match(css1717, /RPG Your Way 1\.7\.17 landing console \+ repository cleanup/)
assert.match(css1717, /\.landing-ai-warning \.landing-notice-card h1/)
assert.match(css1717, /\.landing-player-stack\s*\{/)
assert.match(css1717, /\.landing-new-player\.button/)
assert.match(css1717, /\.landing-return-button\.button/)

console.log('RPG Your Way 1.7.17 landing console and repository cleanup checks passed.')


const landing1718 = read('app/page.tsx')
assert.match(landing1718, /landing-reason-created/)
assert.match(landing1718, /landing-reason-audience/)
assert.match(landing1718, />Start A New Campaign<\/Link>/)
assert.match(landing1718, /Why I created RPG Your Way\./)
assert.match(landing1718, /Who benefits from this site\?/)

const campaign1718 = read('components/LandingCampaignPanel.tsx')
assert.match(campaign1718, /const limit = 360/)
assert.match(campaign1718, /clean\.slice\(-limit\)/)
assert.match(campaign1718, /landing-campaign-summary-card/)
assert.match(campaign1718, /landing-balance-control/)
assert.match(campaign1718, /Return to Adventure/)
assert.match(campaign1718, /<span>\{campaign\.snippet/)

const css1718 = read('app/globals.css')
assert.match(css1718, /RPG Your Way 1\.7\.18 dimensional flat landing system/)
assert.match(css1718, /--landing-mint:/)
assert.match(css1718, /--landing-olive:/)
assert.match(css1718, /\.landing-open-now \.landing-notice-card h2/)
assert.match(css1718, /\.landing-thesis-strip p/)
assert.match(css1718, /\.landing-reason-card summary/)
assert.match(css1718, /\.landing-campaign-summary-card/)
assert.match(css1718, /\.landing-campaign-snippet > span/)
assert.match(css1718, /\.landing-balance-control/)
assert.match(css1718, /grid-template-columns: minmax\(0, \.85fr\) minmax\(0, 1\.45fr\)/)

console.log('RPG Your Way 1.7.18 dimensional landing console checks passed.')


const landing1719 = read('app/page.tsx')
assert.match(landing1719, /landing-return-section--hero/)
assert.match(landing1719, /landing-reason-created/)
assert.match(landing1719, /landing-reason-audience/)
assert.doesNotMatch(landing1719, /landing-notice-pair-section/)
assert.doesNotMatch(landing1719, /landing-thesis-strip/)
assert.doesNotMatch(landing1719, /className="hero-unique landing-reason-card/)
assert.doesNotMatch(landing1719, /className="hero-audience landing-reason-card/)

const campaign1719 = read('components/LandingCampaignPanel.tsx')
assert.match(campaign1719, /const limit = 360/)
assert.match(campaign1719, /clean\.slice\(-limit\)/)
assert.match(campaign1719, /landing-campaign-summary-card/)
assert.match(campaign1719, /landing-balance-control/)
assert.match(campaign1719, /Return to Adventure/)

const css1719 = read('app/globals.css')
assert.match(css1719, /RPG Your Way 1\.7\.19 dimensional landing language/)
assert.match(css1719, /--landing-brass-light:/)
assert.match(css1719, /\.landing-notice-grid/)
assert.match(css1719, /\.landing-notice-grid \.landing-notice-card h1/)
assert.match(css1719, /\.landing-reason-card summary/)
assert.match(css1719, /\.landing-player-stack,\n\.landing-return-logo/)
assert.match(css1719, /\.landing-campaign-summary-card/)
assert.match(css1719, /\.landing-campaign-snippet > span\s*\{\s*-webkit-line-clamp: 5;/)
assert.match(css1719, /\.landing-balance-control\s*\{/)
assert.match(css1719, /\.landing-return-logo\s*\{/)
assert.match(css1719, /aspect-ratio: 1 \/ 1;/)
assert.match(css1719, /white-space: nowrap;/)

console.log('RPG Your Way 1.7.19 dimensional landing language checks passed.')


const campaign1720 = read('components/LandingCampaignPanel.tsx')
assert.match(campaign1720, /const limit = 360/)
assert.match(campaign1720, /clean\.slice\(-limit\)/)

console.log('RPG Your Way 1.7.20 validator tail-limit hotfix checks passed.')


const landing1721 = read('app/page.tsx')
assert.match(landing1721, /PageShell headerVariant="landing"/)
assert.match(landing1721, /Why I created RPG Your Way\./)
assert.match(landing1721, /Who benefits from this site\?/ )
if (landing1721.includes('const features')) {
  assert.match(landing1721, /Play a long-running campaign without waiting for everybody to be free at the same time\.|Run an ongoing tabletop campaign without waiting for a whole group to be free at the same moment\./)
  assert.match(landing1721, /Play one character or run a party of up to six\.|Play one character or manage a full party\./)
  assert.match(landing1721, /Type or talk to your Game Master\.|The interface is being built mobile-first/)
}
assert.doesNotMatch(landing1721, /className="landing-notice-body"/)

const css1721 = read('app/globals.css')
assert.match(css1721, /RPG Your Way 1\.7\.21 dimensional controls \+ human-language pass/)
assert.match(css1721, /--rpgyw-control-hover: var\(--lime\)/)
assert.match(css1721, /\.site-header \.brand:hover/)
assert.match(css1721, /\.landing-notice-body/)
assert.match(css1721, /\.landing-reason-card \.accordion-plus/)
assert.match(css1721, /border: 2px solid var\(--rpgyw-brass-edge\)/)
assert.match(css1721, /color: var\(--rpgyw-control-hover\) !important/)
assert.match(css1721, /body :where\(button, \.button, \.fake-button, summary, \[role="button"\]\)/)

console.log('RPG Your Way 1.7.21 dimensional controls and language checks passed.')


const css1722 = read('app/globals.css')
assert.match(css1722, /RPG Your Way 1\.7\.22 header hover \+ dimensional utility controls/)
assert.match(css1722, /\.site-header \.main-nav a:hover,[\s\S]*background: var\(--forest-deep\);[\s\S]*color: var\(--lime\) !important/)
assert.match(css1722, /\.site-header \.brand-mark[\s\S]*border: 2px solid var\(--landing-brass-mid\)/)
assert.match(css1722, /\.site-header \.fullscreen-toggle[\s\S]*border: 2px solid var\(--landing-brass-mid\)/)
assert.match(css1722, /\.site-header \.fullscreen-toggle:hover,[\s\S]*background: var\(--forest-deep\);[\s\S]*color: var\(--lime\) !important/)
assert.match(css1722, /\.landing-reason-card summary:hover \.landing-accordion-prompt/)
assert.match(read('components/SiteHeader.tsx'), /className="brand-mark"/)
assert.match(read('components/FullscreenToggle.tsx'), /className="fullscreen-toggle"/)

console.log('RPG Your Way 1.7.22 header hover and dimensional utility-control checks passed.')

const css1723 = read('app/globals.css')
assert.match(css1723, /RPG Your Way 1\.7\.23 visual unification/)
assert.match(css1723, /\.shape-main > \.shape-shell,[\s\S]*background: transparent/)
assert.match(css1723, /\.account-intro[\s\S]*border: 2px solid var\(--rpgyw-brass-edge\)/)
assert.match(css1723, /\.aigm-die-button,[\s\S]*background:/)
assert.match(css1723, /\.aigm-send-roll,[\s\S]*var\(--landing-olive-19\)/)
assert.match(css1723, /\.medieval-page--play button:not\(:disabled\):hover,[\s\S]*background: var\(--forest-deep\) !important;[\s\S]*color: var\(--lime\) !important/)
assert.match(read('components/aigm/aigm-gameplay-shell.tsx'), /aigm-die-button/)
assert.match(read('components/aigm/aigm-gameplay-shell.tsx'), /aigm-character-card--leader/)
assert.doesNotMatch(read('app/account/page.tsx'), /className="account-intro"/)

console.log('RPG Your Way 1.7.23 visual-unification checks passed.')


const css1724 = read('app/globals.css')
assert.match(css1724, /RPG Your Way 1\.7\.24 Play visual correction/)
assert.match(css1724, /\.aigm-dice-mode-button[\s\S]*border: 1px solid var\(--rpgyw-brass-edge\)/)
assert.match(css1724, /\.aigm-characters-heading h2[\s\S]*font-size: clamp/)
assert.match(css1724, /\.aigm-conversation-stage[\s\S]*background: var\(--forest-deep\)/)
assert.match(css1724, /\.aigm-conversation-olive-frame[\s\S]*var\(--landing-olive-19-deep\)/)
assert.match(css1724, /\.aigm-conversation-scroll[\s\S]*border: 2px solid var\(--landing-brass-dark\)/)
const gameplay1724 = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplay1724, /aigm-dice-mode-toggle/)
assert.match(gameplay1724, /aigm-conversation-stage/)
assert.match(gameplay1724, /aigm-conversation-olive-frame/)

console.log('RPG Your Way 1.7.24 Play visual-correction checks passed.')


const css1725 = read('app/globals.css')
assert.match(css1725, /RPG Your Way 1\.7\.25 Play rail repair \+ landing bezel/)
assert.match(css1725, /\.aigm-dice-mode-toggle[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
assert.match(css1725, /\.aigm-party-capacity[\s\S]*text-align: center/)
assert.match(css1725, /\.landing-campaign-screen-stage[\s\S]*background: var\(--forest-deep\)/)
assert.match(css1725, /\.landing-campaign-screen-olive-frame[\s\S]*var\(--landing-olive-19-deep\)/)
const gameplay1725 = read('components/aigm/aigm-gameplay-shell.tsx')
assert.match(gameplay1725, /Current party:/)
assert.match(gameplay1725, /Max party size:/)
assert.doesNotMatch(gameplay1725, /\{readyCharacters\.length\} · Max 6/)
assert.match(read('components/LandingCampaignPanel.tsx'), /landing-campaign-screen-stage/)
assert.match(read('components/LandingCampaignPanel.tsx'), /landing-campaign-screen-olive-frame/)

console.log('RPG Your Way 1.7.25 Play rail and landing-bezel checks passed.')

const authPanel1726 = read('components/AuthPanel.tsx')
assert.match(authPanel1726, /<span>Email address<\/span>/)
assert.match(authPanel1726, /name="email"/)
assert.match(authPanel1726, /name="confirmPassword"/)
assert.doesNotMatch(authPanel1726, /confirmEmail/)
assert.doesNotMatch(authPanel1726, /Confirm your email address/)
const authActions1726 = read('app/account/actions.ts')
assert.doesNotMatch(authActions1726, /confirmEmail/)
assert.doesNotMatch(authActions1726, /email addresses do not match/)
assert.match(authActions1726, /Enter your email address and choose a password\./)
assert.match(authActions1726, /password !== confirmPassword/)
const authPrompt1726 = read('components/AuthPrompt.tsx')
assert.ok(authPrompt1726.indexOf('Not now. I just want to look around.') < authPrompt1726.indexOf('<AuthPanel'), 'Not-now control must appear above the sign-in/create-account cards.')
const css1726 = read('app/globals.css')
assert.match(css1726, /RPG Your Way 1\.7\.26 account-entry cleanup/)
assert.match(css1726, /\.auth-dialog-footer \{ display: block; margin: 0 0 \.8rem; \}/)

console.log('RPG Your Way 1.7.26 account-entry cleanup checks passed.')


const css1727 = read('app/globals.css')
const header1727 = read('components/SiteHeader.tsx')
assert.match(css1727, /RPG Your Way 1\.7\.27 account dimensional pass \+ quiet-at-rest accents/)
assert.match(css1727, /\.account-main \.account-intro,[\s\S]*border: 2px solid var\(--rpgyw-brass-edge\) !important/)
assert.match(css1727, /\.account-main \.auth-card,[\s\S]*var\(--landing-mint-19\)/)
assert.match(css1727, /\.feature-card:nth-child\(2\) \.feature-eyebrow \{\s*color: var\(--cream-bright\);/)
assert.match(css1727, /\.kofi-support-button \{[\s\S]*color: var\(--lime\);/)
assert.match(css1727, /\.kofi-support-button:hover \{[\s\S]*color: var\(--lime\);/)
assert.match(header1727, /className="nav-external-arrow"/)
assert.match(header1727, />↗<\/span>/)
assert.match(header1727, /opens in a new tab/)

console.log('RPG Your Way 1.7.27 account styling, quiet accents, and Read external-link cue checks passed.')


const css1728 = read('app/globals.css')
assert.match(css1728, /RPG Your Way 1\.7\.28 landing feature nameplates/)
assert.match(css1728, /\.feature-card \{[\s\S]*var\(--landing-pale\)/)
assert.match(css1728, /\.feature-eyebrow \{[\s\S]*border: 2px solid var\(--landing-brass-mid\)/)
assert.match(css1728, /\.feature-card:nth-child\(1\) \.feature-eyebrow,[\s\S]*\.feature-card:nth-child\(3\) \.feature-eyebrow[\s\S]*background:[\s\S]*var\(--forest-deep\)/)
assert.match(css1728, /\.feature-card:nth-child\(2\) \.feature-eyebrow \{[\s\S]*var\(--landing-pale\)[\s\S]*color: var\(--forest-deep\)/)
assert.match(css1728, /\.feature-card:nth-child\(2\) \{[\s\S]*var\(--forest-deep\)[\s\S]*color: var\(--cream-bright\);/)
assert.match(css1728, /\.feature-card:nth-child\(2\) h3 \{\s*color: var\(--cream-bright\);/)
assert.match(css1728, /\.feature-card:nth-child\(2\) > p:last-child \{\s*color: var\(--cream-bright\);/)

console.log('RPG Your Way 1.7.28 landing feature-nameplate checks passed.')


const landing1730 = read('app/page.tsx')
const persistent1730 = read('components/PersistentPlayModal.tsx')
const css1730 = read('app/globals.css')
assert.match(landing1730, /persistentPlay: true/)
assert.match(landing1730, /<PersistentPlayModal \/>/)
assert.match(landing1730, /Play when you have time/)
assert.match(persistent1730, /Persistent Campaign\?/)
assert.match(persistent1730, /what the hell do we mean by persistent play\?/)
assert.match(persistent1730, /three hundred turns later/)
assert.match(persistent1730, /Tell it to look it up\./)
assert.match(persistent1730, /Five\. The robot doesn’t eat\./)
assert.match(persistent1730, /Work with your AI, not against it\./)
assert.match(css1730, /RPG Your Way 1\.7\.30: three-line premise plaque \+ persistent-play explanation/)
assert.match(css1730, /\.landing-reason-card \.persistent-play-close-x \{[\s\S]*width: 40px !important/)
assert.match(css1730, /\.landing-reason-card \.persistent-play-modal-footer button \{[\s\S]*background: var\(--forest-deep\) !important/)
assert.match(css1730, /\.persistent-play-thesis,[\s\S]*color: var\(--cream-bright\) !important/)


assert.match(gameplayShell, /aigm-topbar-nameplate/)
assert.match(gameplayShell, /aigm-gameplay-gm/)
assert.doesNotMatch(gameplayShell, /Accept what fate sends your way/)
assert.doesNotMatch(gameplayShell, /HP, AC, conditions, currency, and tracked resources update/)
assert.match(css, /RPG Your Way 1\.7\.31/)
console.log('RPG Your Way 1.7.31 compact Play header and rail-space checks passed.')


assert.match(gameplayShell, /aigm-gameplay-heading-copy/)
assert.match(gameplayShell, /<div className="aigm-character-footer">[\s\S]*Add another character<\/button>[\s\S]*<div className="aigm-character-memory-note/ )
assert.match(css, /RPG Your Way 1\.7\.32/)
assert.match(css, /\.aigm-dice-heading,[\s\S]*height: fit-content !important/)
assert.match(css, /\.aigm-dice-mode-toggle,[\s\S]*margin-top: 0 !important/)
assert.match(css, /\.aigm-gameplay-heading-copy \{[\s\S]*flex-direction: column/)
assert.match(css, /\.aigm-gameplay-meta \{[\s\S]*white-space: normal/)
console.log('RPG Your Way 1.7.32 Play rail-heading, campaign-header, and character-list flow checks passed.')


assert.match(css, /RPG Your Way 1\.7\.33: Play-only desktop header width/)
assert.match(css, /\.play-page-frame > \.site-header \.header-inner \{[\s\S]*width: calc\(100% - 1rem\)[\s\S]*max-width: none/)
assert.match(css, /@media \(min-width: 861px\) \{[\s\S]*\.play-page-frame \.aigm-gameplay-grid \{[\s\S]*grid-template-columns: minmax\(230px, \.68fr\) minmax\(0, 2\.85fr\) minmax\(240px, \.72fr\)/)
assert.match(css, /\.play-page-frame \.aigm-mobile-nav \{[\s\S]*display: none !important/)
assert.match(css, /\.aigm-dice-mode-button:not\(\.aigm-dice-mode-button--active\):hover,[\s\S]*color: var\(--lime\) !important/)
assert.match(css, /\.aigm-dice-mode-button--active,[\s\S]*color: var\(--cream-bright\) !important/)
console.log('RPG Your Way 1.7.33 Play desktop-layout, header-width, and dice-mode-state checks passed.')

assert.match(gameplay1714, /<span className="text-center leading-tight">Story<br \/>first<\/span>/)
console.log('RPG Your Way 1.7.34 Story-first two-line centering check passed.')

assert.match(gameplayShell, /aigm-character-memory-note/)
assert.match(css, /RPG Your Way 1\.7\.35/)
assert.match(css, /\.aigm-character-memory-note > svg \{[\s\S]*float: left/)
console.log('RPG Your Way 1.7.35 character-rail final-flow cleanup check passed.')


const start180 = read('components/start/StartOnboarding.tsx')
const startEntry180 = read('components/aigm/rpgyw-start-entry.tsx')
const accountActions180 = read('app/account/actions.ts')
const accountPage180 = read('app/account/page.tsx')
const footer180 = read('components/SiteFooter.tsx')
const css180 = read('app/globals.css')

// 1.8 current Start onboarding contract.
assert.match(start180, /I need help with all of this/)
assert.match(start180, /My question wasn&apos;t above\. I still need help\./)
assert.match(start180, /25 free questions remaining in this onboarding session/)
assert.match(start180, /Choose the game rules/)
assert.match(start180, /The Uncharted Realms/)
assert.match(start180, /D&D 5\.5e/)
assert.match(start180, /<span>2<\/span>Gather Your Party/)
assert.match(start180, /Choose from<br \/>ready-to-play characters/)
assert.match(start180, /And\/or browse for<br \/>your character files/)
assert.match(start180, /And\/or paste your<br \/>character&apos;s information/)
assert.match(start180, /Character import help/)
assert.doesNotMatch(start180, /About ready-to-play characters/)
assert.match(start180, /File added/)
assert.match(start180, /Import into RPG Your Way/)
assert.match(start180, /Required before this character can be used/)
assert.match(start180, /Recommended before play/)
assert.match(start180, /Names and portraits can be changed later on the Play page through the Characters sidebar/)
assert.doesNotMatch(start180, /or drag files here/)
assert.match(start180, /Proposed party leader:/)
assert.doesNotMatch(start180, />Keep<\/button>/)
assert.match(start180, /How did we choose this leader\?/)
assert.match(start180, /Strength override/)
assert.match(start180, /<span>3<\/span>Adjustable gameplay settings/)
assert.match(start180, />Customize<\/button>/)
assert.match(start180, />Use default settings<\/button>/)
assert.match(start180, /How weird do you want your campaign to get\?/)
assert.match(start180, /Grounded and local/)
assert.match(start180, /Reality-bending and cosmic/)
assert.match(start180, /Long-term story direction/)
assert.match(start180, /rows=\{3\}/)
assert.match(start180, /start-field-bezel/)
assert.match(start180, /Descriptive campaign name here — have fun/)
assert.match(start180, /placeholder="Game Master name"/)
assert.doesNotMatch(start180, /The Sharn Chronicles/)
assert.doesNotMatch(start180, /Malcolm/)
assert.doesNotMatch(start180, /UI review build: character standardization/)
assert.doesNotMatch(start180, /Male · Fable/)
assert.doesNotMatch(start180, /Female · Marin/)
assert.match(start180, /'Onward'/)
assert.match(start180, /Importing a normal character is generally free/)
assert.match(start180, /before additional AI processing uses part of your available usage balance/)

assert.match(startEntry180, /<StartOnboarding \/>/)
assert.match(startEntry180, /Already have an RPG Your Way or WardensPC adventure\?/)
assert.match(startEntry180, /site-frame site-frame-play site-frame-start/)
assert.match(accountActions180, /admin\.auth\.admin\.deleteUser/)
assert.match(accountActions180, /confirmation !== 'DELETE'/)
assert.match(accountPage180, /<DeleteAccountControl \/>/)
assert.match(footer180, /mailto:brett@rpgyourway\.com/)
assert.match(footer180, />Contact</)

assert.doesNotMatch(css180, /--lime: #00ff00/)
assert.match(css180, /RPG Your Way 1\.8\.6/)
assert.match(css180, /\.site-frame-start \.start-page-main > \.start-page-shell \{[\s\S]*background: transparent/)
assert.match(css180, /\.start-step-nameplate,[\s\S]*border: 3px solid var\(--rpgyw-brass-highlight\)/)
assert.match(css180, /\.start-drop-zone \{[\s\S]*border: 7px solid var\(--landing-olive-19-deep\)/)
assert.match(css180, /\.start-settings-bezel \{[\s\S]*border: 7px solid var\(--landing-olive-19-deep\)/)
assert.match(css180, /\.start-question-textarea \{[\s\S]*border: 7px solid var\(--landing-olive-19-deep\)/)
assert.match(css180, /\.start-rating-scale button\.is-selected \{[\s\S]*var\(--forest-deep\)/)
assert.match(css180, /\.start-mini-ratings label \{[\s\S]*border: 2px solid var\(--rpgyw-brass-highlight\)/)
assert.match(css180, /\.start-field-bezel \{[\s\S]*border: 7px solid var\(--landing-olive-19-deep\)/)
console.log('RPG Your Way 1.8.6 Start open-map, dimensional-controls, question-scale, and naming-bezel checks passed.')


const start187 = read('components/start/StartOnboarding.tsx')
const intake187 = read('app/api/aigm/character-intake/route.ts')
const clarify187 = read('app/api/aigm/character-clarify/route.ts')
const help187 = read('app/api/start/help/route.ts')
const prompt187 = read('lib/aigm/character-intake-prompt.ts')
assert.match(start187, /Import into RPG Your Way/)
assert.match(start187, /Required before this character can be used/)
assert.match(start187, /Recommended before play/)
assert.match(start187, /Continue without these answers/)
assert.match(start187, /Names and portraits can be changed later on the Play page through the Characters sidebar\./)
assert.match(start187, /window\.location\.assign\('\/play'\)/)
assert.match(start187, /saveAdventureState/)
assert.doesNotMatch(start187, /or drag files here/)
assert.doesNotMatch(start187, /start-drop-zone/)
assert.match(intake187, /paid_intake_confirmation_required/)
assert.match(intake187, /allow_paid/)
assert.match(intake187, /reserveUsage/)
assert.match(intake187, /settleUsage/)
assert.match(clarify187, /bill_usage/)
assert.match(help187, /START_HELP_KNOWLEDGE/)
assert.match(help187, /max_output_tokens: 500/)
assert.match(help187, /MAX_QUESTIONS_PER_HOUR = 25/)
assert.match(start187, /activeImportWorkflow/)
assert.match(start187, /Finish importing .* before starting another character/)
assert.match(prompt187, /Separate clarification questions into two tiers/)
assert.match(css, /RPG Your Way 1\.8\.7/)
assert.doesNotMatch(css, /start-file-drop-control/)
assert.match(css, /start-clarification-tier/)
assert.match(css, /site-header \.brand-mark \{ width: 44px; height: 44px;/)
console.log('RPG Your Way 1.8.7 functional Start import, clarification, help, campaign creation, footer, and compass checks passed.')

const start188 = read('components/start/StartOnboarding.tsx')
assert.match(start188, /useState<1 \| 2 \| 3 \| 4>\(1\)/)
assert.match(start188, /activeStep === 1/)
assert.match(start188, /\(default\)/)
assert.match(start188, /or choose a different one/)
assert.match(start188, /Use these game rules/)
assert.match(start188, /<strong>Selected:<\/strong>/)
assert.match(start188, /setActiveStep\(2\)/)
assert.match(start188, /activeStep === 2/)
assert.match(start188, /activeStep === 3 && partyReady/)
assert.match(start188, /activeStep === 4 && questionsDone/)
assert.match(start188, /Or reset everything and start again/)
assert.doesNotMatch(start188, /Current default/)
assert.doesNotMatch(start188, /<p className="start-fixed-setting"><strong>Setting:<\/strong> The Uncharted Realms<\/p>/)
assert.match(css, /RPG Your Way 1\.8\.8/)
assert.match(css, /start-rules-card--single-step/)
assert.match(css, /start-reset-link/)
console.log('RPG Your Way 1.8.8 sequential Step 1 game-rules board checks passed.')


const start189 = read('components/start/StartOnboarding.tsx')
const help189 = read('lib/start/help-knowledge.ts')
assert.match(start189, /<span>2<\/span>Gather Your Party/)
assert.match(start189, /Names and portraits can be changed later on the Play page through the Characters sidebar\./)
assert.doesNotMatch(start189, /Click on whoever you want to edit/)
assert.doesNotMatch(start189, /or drag files here/)
assert.doesNotMatch(start189, /onDrop=\{onBrowseDrop\}/)
assert.doesNotMatch(start189, /DragEvent/)
assert.match(start189, /remainingPartySlots = Math\.max\(0, 6 - party\.length\)/)
assert.match(start189, /Current party: \{party\.length\} · \{remainingPartySlots\}/)
assert.match(start189, /setImportMessage\(''\)[\s\S]*setParty\(\(current\) => current\.filter/)
assert.match(start189, /sourceFileKey/)
assert.match(start189, /duplicate character file/)
assert.match(start189, />Use this party<\/button>/)
assert.match(start189, /setActiveStep\(3\)/)
assert.match(start189, /questionsDone \? <div className="start-settings-leader"/)
assert.match(start189, /Proposed party leader:/)
assert.match(start189, /start-step-continue/)
assert.match(help189, /browsing for the file/)
assert.doesNotMatch(help189, /browsing or dragging/)
assert.match(css, /RPG Your Way 1\.8\.9/)
assert.match(css, /\.start-party-note/)
assert.match(css, /\.start-party-confirm/)
assert.match(css, /\.start-settings-leader/)
console.log('RPG Your Way 1.8.9 Step 2 party-count, no-drag, plain-note, duplicate-file, and deferred-leader checks passed.')


const start1810 = read('components/start/StartOnboarding.tsx')
const voice1810 = read('components/aigm/aigm-voice-controls.tsx')
const transcribe1810 = read('app/api/aigm/transcribe/route.ts')
const speech1810 = read('app/api/aigm/speech/route.ts')
const transcriptionGuard1810 = read('lib/aigm/transcription-guard.ts')
assert.match(start1810, /<span>4<\/span><strong id="names-heading">The naming of the names<\/strong>/)
assert.match(start1810, /<span className="sr-only">Campaign name<\/span>/)
assert.match(start1810, /<span className="sr-only">Game Master name<\/span>/)
assert.doesNotMatch(start1810, /Give your campaign a fun name<\/span>/)
assert.doesNotMatch(start1810, /What do you want to call your Game Master\?<\/span>/)
assert.match(start1810, /helpConversation/)
assert.match(start1810, /start-ai-dialogue/)
assert.match(start1810, /AigmVoiceControls/)
assert.match(start1810, /profile="onboarding" assistantName="Start Page Help"/)
assert.match(start1810, /profile="onboarding" assistantName="RPG Your Way"/)
assert.match(start1810, /clarificationConversation/)
assert.match(start1810, /Required before this character can be used/)
assert.match(start1810, /Recommended before play/)
assert.match(start1810, /data-aigm-manual-listen="true"/)
assert.match(voice1810, /assistantName\?\.trim\(\) \|\| \(onboardingProfile \? 'RPG Your Way' : 'Game Master'\)/)
assert.doesNotMatch(voice1810, /Ithamir’s voice/)
assert.match(transcribe1810, /form\.get\('context'\) === 'onboarding'/)
assert.match(transcribe1810, /transcriptionPromptFor\(context\)/)
assert.match(speech1810, /profile === 'onboarding'/)
assert.match(speech1810, /onboarding or setup-help reply/)
assert.doesNotMatch(transcriptionGuard1810, /for Ithamir/)
assert.match(css, /RPG Your Way 1\.8\.10/)
assert.match(css, /\.start-ai-turn--assistant/)
assert.match(css, /\.start-ai-composer/)
console.log('RPG Your Way 1.8.10 Start dialogue, default-readback controls, and naming-step cleanup checks passed.')

const css1811 = read('app/globals.css')
assert.match(css1811, /RPG Your Way 1\.8\.11/)
assert.match(css1811, /--rpgyw-pale-olive: #dde2b9/)
assert.match(css1811, /--rpgyw-pale-olive-light: #edf0d4/)
assert.match(css1811, /--rpgyw-pale-olive-deep: #c8d09b/)
assert.match(css1811, /--landing-mint: var\(--rpgyw-pale-olive\)/)
assert.match(css1811, /--landing-mint-19: var\(--rpgyw-pale-olive\)/)
assert.doesNotMatch(css1811, /#d9e2cf|#e8eddf|#dce5d3|#c7d4bc/i)
assert.match(css1811, /body :where\(button, \.button, \.fake-button, summary, \[role="button"\]\)/)
assert.match(css1811, /0 0 0 var\(--rpgyw-rim-spread\) var\(--rpgyw-brass-edge\)/)
assert.match(css1811, /section\[role="dialog"\]/)
assert.match(css1811, /border: 5px solid var\(--landing-olive-19-deep\) !important/)
assert.match(css1811, /\.site-footer \.kofi-support-button/)
assert.match(css1811, /body a\[class\*=\"rounded\"\]\[class\*=\"border\"\]/)
assert.match(css1811, /\.landing-notice-grid \.landing-notice-card h1,[\s\S]*0 0 0 3px var\(--rpgyw-brass-edge\)/)
console.log('RPG Your Way 1.8.11 pale-olive palette, standardized brass furniture, inset bezels, popup, and Ko-fi checks passed.')

const turnBilling1812 = read('lib/usage/play-turn-billing.ts')
const audioCost1812 = read('lib/usage/audio-cost.ts')
const speech1812 = read('app/api/aigm/speech/route.ts')
const transcribe1812 = read('app/api/aigm/transcribe/route.ts')
const voice1812 = read('components/aigm/aigm-voice-controls.tsx')
const shell1812 = read('components/aigm/aigm-gameplay-shell.tsx')
const account1812 = read('app/account/page.tsx')
const migration1812 = read('supabase/migrations/20260828002500_play_turn_voice_billing.sql')
assert.match(turnBilling1812, /roundUsageMicrousdToCent\(providerTotal\)/)
assert.match(turnBilling1812, /component_type === 'ttt'/)
assert.match(turnBilling1812, /component_type === 'gameplay'/)
assert.match(turnBilling1812, /component_type === 'tts'/)
assert.match(turnBilling1812, /rpgyw_capture_usage/)
assert.match(turnBilling1812, /ownerQa \? 0/)
assert.match(audioCost1812, /Math\.ceil\(\(usage\.inputTokens \* 5 \+ usage\.outputTokens \* 20\) \/ 4\)/)
assert.match(audioCost1812, /TTS_ESTIMATED_MICROUSD_PER_SECOND = 250/)
assert.match(speech1812, /response_format: 'wav'/)
assert.match(speech1812, /OPENAI_TTS_API_KEY/)
assert.match(speech1812, /billingMode === 'replay'/)
assert.match(transcribe1812, /OPENAI_TRANSCRIBE_API_KEY/)
assert.match(transcribe1812, /await upstream\.json/)
assert.doesNotMatch(transcribe1812, /stream=true|stream', 'true'/)
assert.match(transcribe1812, /usable_transcript: false/)
assert.match(voice1812, /billing_turn_id: billingTurnId/)
assert.match(voice1812, /expected_tts_components/)
assert.match(shell1812, /exchangeId = turnBillingId/)
assert.match(shell1812, /draftTurnBillingIdRef/)
assert.match(shell1812, /balanceMicrousd <= 1_000_000/)
assert.match(account1812, /rpgyw_usage_summary/)
assert.match(account1812, /rpgyw_purchase_history/)
assert.match(account1812, /available <= 1_000_000/)
assert.doesNotMatch(account1812, /\.from\('usage_ledger'\)/)
assert.match(css1811, /RPG Your Way 1\.8\.12 account usage summary/)
assert.match(css1811, /\.account-main \.usage-summary-grid/)
assert.match(css1811, /\.account-main \.usage-estimate-row/)
assert.match(migration1812, /create table if not exists public\.play_turn_billing/)
assert.match(migration1812, /create table if not exists public\.play_turn_components/)
assert.match(migration1812, /drop policy if exists "usage_ledger_select_own"/)
assert.match(migration1812, /create or replace function public\.rpgyw_usage_summary\(\)/)
assert.match(migration1812, /create or replace function public\.rpgyw_purchase_history/)
assert.match(migration1812, /grant execute on function public\.rpgyw_usage_summary\(\) to authenticated/)
const css190 = read('app/globals.css')
assert.match(css190, /RPG Your Way 1\.9\.0 Play readability pass/)
assert.match(css190, /\.aigm-session-tools-toggle/)
assert.match(css190, /\.aigm-latest-turn/)
assert.match(css190, /\.aigm-character-card/)
assert.match(home, /href="\/start">Start A New Campaign<\/Link>/)
assert.match(gameplayShell, /aigm-session-tools-toggle/)
assert.match(gameplayShell, /aigm-latest-turn/)

console.log('RPG Your Way 1.9.0 Play readability and landing-copy checks passed.')


const css191 = read('app/globals.css')
assert.match(css191, /RPG Your Way 1\.9\.1 character-card surface correction/)
assert.match(css191, /\.medieval-page--play \.aigm-character-card > button \{[\s\S]*?background: var\(--background\) !important;/)
assert.match(css191, /RPG Your Way 1\.9\.2 landing-page ribbon \+ hero reset/)
assert.match(css191, /\.site-brand-ribbon \{/)
assert.match(css191, /\.landing-campaign-snippet--preview \{/)
const account194 = read('app/account/page.tsx')
assert.match(account194, /<h1 className="sr-only">Account<\/h1>/)
assert.doesNotMatch(account194, /<section className="account-intro"/)
assert.doesNotMatch(account194, /Your account\./)
assert.doesNotMatch(account194, /Sign in, see your RPG Your Way balance, and add usage for Play or Script\./)
assert.match(account194, /statusMessages\[status\]/)
assert.match(account194, /paymentNotice/)
assert.match(account194, /paymentError/)
console.log('RPG Your Way 1.9.4 account-intro removal checks passed.')


const accessibility1100 = read('app/accessibility/page.tsx')
const accessibilityStandard1100 = read('ACCESSIBILITY.md')
const accessibilityValidator1100 = read('scripts/validate-accessibility.mts')
const header1100 = read('components/SiteHeader.tsx')
const footer1100 = read('components/SiteFooter.tsx')
const start1100 = read('components/start/StartOnboarding.tsx')
const deleteAccount1100 = read('components/account/DeleteAccountControl.tsx')
const gameplay1100 = read('components/aigm/aigm-gameplay-shell.tsx')
const css1100 = read('app/globals.css')
assert.match(accessibility1100, /Web Content Accessibility Guidelines/)
assert.match(accessibility1100, /WCAG<\/abbr> 2\.2 Level AA/)
assert.match(accessibility1100, /does not claim independent certification/)
assert.match(accessibilityStandard1100, /WCAG 2\.2 Level AA/)
assert.match(accessibilityStandard1100, /NVDA \+ Firefox or Chrome/)
assert.match(accessibilityValidator1100, /accessibility regression checks passed/)
assert.match(pkg['scripts']?.['validate:release'] ?? '', /validate-accessibility\.mts/)
assert.match(header1100, /usePathname/)
assert.match(header1100, /aria-current=/)
assert.match(footer1100, /href="\/accessibility"/)
assert.match(start1100, /useAccessibleDialog<HTMLElement>/)
assert.match(start1100, /role="log" aria-live="polite"/)
assert.match(deleteAccount1100, /aria-describedby="delete-account-confirm-help"/)
assert.match(gameplay1100, /aria-label="Your gameplay action or message"/)
assert.match(gameplay1100, /mobilePanelFocusReadyRef/)
assert.match(css1100, /RPG Your Way 1\.10\.0 accessibility foundation/)
assert.match(css1100, /@media \(forced-colors: active\)/)
console.log('RPG Your Way 1.10.0 accessibility foundation checks passed.')
